import { Navigate, Route, Routes } from 'react-router-dom'
import { AppShell } from '../layouts/AppShell'
import { Asset360Page } from '../pages/Asset360Page'
import { DashboardPage } from '../pages/DashboardPage'
import { FindingDetailPage } from '../pages/FindingDetailPage'
import { LoginPage } from '../pages/LoginPage'
import { MFAPage } from '../pages/MFAPage'
import { ResourcePage } from '../pages/ResourcePage'
const routes=[['assets','Assets','Organization-scoped inventory and Asset 360 entry points.'],['network-health','Network Health','Availability, latency, packet loss, DNS, HTTP, TLS, routes and agent health.'],['diagnostics','Diagnostics','Safe diagnostic requests resolved only from an approved Authorized Scope.'],['jobs','Jobs','Guarded analysis jobs and transparent state transitions.'],['findings','Findings','Actionable conclusions with separate severity, priority and confidence.'],['vulnerabilities','Vulnerabilities','Scanner evidence enriched with NVD and known-exploitation context.'],['traffic','Traffic','Normalized connection, protocol and IDS observations.'],['pcap','PCAP','Sensitive packet captures with explicit access and short retention.'],['agents','Agents','Outbound-connected sensors, capabilities and cryptographic identity.'],['scopes','Authorized Scopes','Verified targets and validity windows required for active execution.'],['modules','Modules','Versioned adapters with schemas, capabilities and declared risk classes.'],['reports','Reports','Evidence-backed health, security, exposure and PCAP reports.'],['users','Users & Roles','Multi-organization users, MFA policy and granular RBAC.'],['roles','Roles','Granular permissions without implicit public assessment rights.'],['audit','Audit','Security-relevant events prepared for tamper-evident chaining.'],['settings','Settings','Organization policy, retention and operational configuration.']] as const
export function App(){return <Routes><Route path="/login" element={<LoginPage/>}/><Route path="/mfa" element={<MFAPage/>}/><Route path="/app" element={<AppShell/>}><Route index element={<DashboardPage/>}/><Route path="assets/:id" element={<Asset360Page/>}/><Route path="findings/:id" element={<FindingDetailPage/>}/><Route path="jobs/:id" element={<ResourcePage title="Job Detail" description="Execution state, normalized parameters, Scan Guard decision and evidence."/>}/><Route path="agents/:id" element={<ResourcePage title="Agent Detail" description="Identity fingerprint, state, capabilities and compatible modules."/>}/>{routes.map(([path,title,description])=><Route key={path} path={path} element={<ResourcePage title={title} description={description}/>}/>)}</Route><Route path="*" element={<Navigate to="/login" replace/>}/></Routes>}
