CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE scope_environment AS ENUM ('INTERNAL','PUBLIC');
CREATE TYPE normalized_status AS ENUM ('HEALTHY','INFORMATIONAL','ATTENTION','WARNING','CRITICAL','INCONCLUSIVE');
CREATE TYPE confidence_level AS ENUM ('HIGH','MEDIUM','LOW');
CREATE TYPE module_risk_class AS ENUM ('PASSIVE','SAFE_ACTIVE','CONTROLLED_ACTIVE');
CREATE TYPE job_status AS ENUM ('PENDING','QUEUED','ASSIGNED','RUNNING','SUCCEEDED','FAILED','CANCELLED','TIMED_OUT','REJECTED');

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text NOT NULL UNIQUE, timezone text NOT NULL DEFAULT 'UTC', require_mfa boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, email text NOT NULL, password_hash text NOT NULL, active boolean NOT NULL DEFAULT true, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), disabled_at timestamptz, UNIQUE(organization_id,email));
CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES organizations(id), name text NOT NULL, system boolean NOT NULL DEFAULT false, UNIQUE(organization_id,name));
CREATE TABLE permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, description text NOT NULL);
CREATE TABLE role_permissions (role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE, permission_id uuid NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role_id,permission_id));
CREATE TABLE user_roles (user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE, PRIMARY KEY(user_id,role_id));
CREATE TABLE sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(), ip_hash text, user_agent_hash text);
CREATE INDEX sessions_active_user_idx ON sessions(organization_id,user_id,expires_at) WHERE revoked_at IS NULL;
CREATE TABLE mfa_configurations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE UNIQUE, encrypted_totp_secret bytea NOT NULL, enabled boolean NOT NULL DEFAULT false, recovery_code_hashes text[] NOT NULL DEFAULT '{}', verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE mfa_login_challenges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE authorized_scopes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), type text NOT NULL CHECK(type IN ('HOSTNAME','IP','CIDR','URL')), value text NOT NULL, environment scope_environment NOT NULL, status text NOT NULL CHECK(status IN ('PENDING','VERIFIED','APPROVED','REVOKED','EXPIRED')), verification_type text, verified_at timestamptz, verified_by uuid REFERENCES users(id), valid_from timestamptz NOT NULL, valid_until timestamptz NOT NULL, notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), CHECK(valid_until > valid_from), UNIQUE(organization_id,type,value));
CREATE INDEX authorized_scopes_active_idx ON authorized_scopes(organization_id,status,valid_until);
CREATE TABLE assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, type text NOT NULL CHECK(type IN ('HOST','SERVER','WORKSTATION','NETWORK_DEVICE','SERVICE','DOMAIN','URL','OTHER')), hostname text, ip_address inet, environment scope_environment NOT NULL, criticality text NOT NULL CHECK(criticality IN ('LOW','MEDIUM','HIGH','CRITICAL')), owner text, description text, first_seen_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(), status normalized_status NOT NULL DEFAULT 'INFORMATIONAL', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX assets_org_last_seen_idx ON assets(organization_id,last_seen_at DESC);

CREATE TABLE agents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, hostname text NOT NULL, os text NOT NULL, arch text NOT NULL, version text NOT NULL, status text NOT NULL CHECK(status IN ('PENDING','ONLINE','DEGRADED','OFFLINE','REVOKED')), last_seen_at timestamptz, registered_at timestamptz NOT NULL DEFAULT now(), capabilities jsonb NOT NULL DEFAULT '[]', labels jsonb NOT NULL DEFAULT '{}', network_zone text, identity_fingerprint text NOT NULL, identity_rotated_at timestamptz);
CREATE INDEX agents_org_status_idx ON agents(organization_id,status);
CREATE TABLE agent_enrollment_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), token_hash text NOT NULL UNIQUE, created_by uuid NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL, used_at timestamptz, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE module_definitions (id text PRIMARY KEY, name text NOT NULL, version text NOT NULL, category text NOT NULL, risk_class module_risk_class NOT NULL, supported_environments scope_environment[] NOT NULL, required_capabilities text[] NOT NULL, default_timeout_seconds integer NOT NULL CHECK(default_timeout_seconds > 0), input_schema jsonb NOT NULL, result_schema jsonb NOT NULL, enabled boolean NOT NULL DEFAULT true);
INSERT INTO module_definitions(id,name,version,category,risk_class,supported_environments,required_capabilities,default_timeout_seconds,input_schema,result_schema) VALUES
('network.ping','Ping','0.1.0','diagnostics','SAFE_ACTIVE','{INTERNAL,PUBLIC}','{ping}',30,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('network.route','Route','0.1.0','diagnostics','SAFE_ACTIVE','{INTERNAL,PUBLIC}','{route}',60,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('network.dns','DNS','0.1.0','diagnostics','SAFE_ACTIVE','{INTERNAL,PUBLIC}','{dns}',15,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('network.tcp','TCP reachability','0.1.0','diagnostics','SAFE_ACTIVE','{INTERNAL,PUBLIC}','{tcp}',15,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('network.http','HTTP health','0.1.0','diagnostics','SAFE_ACTIVE','{INTERNAL,PUBLIC}','{http}',30,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('network.tls','TLS inspection','0.1.0','diagnostics','SAFE_ACTIVE','{INTERNAL,PUBLIC}','{tls}',20,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('nmap.discovery','Restricted discovery','0.1.0','inventory','CONTROLLED_ACTIVE','{INTERNAL,PUBLIC}','{nmap}',300,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('nmap.services','Authorized service inventory','0.1.0','inventory','CONTROLLED_ACTIVE','{INTERNAL,PUBLIC}','{nmap}',600,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('traffic.tshark','TShark PCAP metadata','0.1.0','traffic','PASSIVE','{INTERNAL,PUBLIC}','{tshark}',1800,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('traffic.zeek','Zeek PCAP analysis','0.1.0','traffic','PASSIVE','{INTERNAL,PUBLIC}','{zeek}',1800,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('security.suricata','Suricata PCAP analysis','0.1.0','security','PASSIVE','{INTERNAL,PUBLIC}','{suricata}',1800,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('vulnerability.greenbone','Greenbone authorized assessment','0.1.0','vulnerability','CONTROLLED_ACTIVE','{INTERNAL,PUBLIC}','{greenbone}',14400,'{"type":"object","additionalProperties":false}','{"type":"object"}'),
('performance.iperf3','Controlled performance test','0.1.0','performance','CONTROLLED_ACTIVE','{INTERNAL}','{iperf3}',120,'{"type":"object","additionalProperties":false}','{"type":"object"}');

CREATE TABLE analysis_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), module_id text NOT NULL REFERENCES module_definitions(id), asset_id uuid REFERENCES assets(id), scope_id uuid NOT NULL REFERENCES authorized_scopes(id), agent_id uuid NOT NULL REFERENCES agents(id), requested_by uuid NOT NULL REFERENCES users(id), parameters jsonb NOT NULL, normalized_target text NOT NULL, risk_class module_risk_class NOT NULL, status job_status NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), queued_at timestamptz, started_at timestamptz, completed_at timestamptz, timeout_at timestamptz NOT NULL, status_version integer NOT NULL DEFAULT 0, rejection_code text, CHECK(jsonb_typeof(parameters)='object'));
CREATE INDEX jobs_org_status_created_idx ON analysis_jobs(organization_id,status,created_at DESC);
CREATE INDEX jobs_agent_queue_idx ON analysis_jobs(agent_id,status,queued_at) WHERE status IN ('QUEUED','ASSIGNED');
CREATE TABLE schedules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), module_id text NOT NULL REFERENCES module_definitions(id), scope_id uuid NOT NULL REFERENCES authorized_scopes(id), agent_id uuid NOT NULL REFERENCES agents(id), frequency_seconds integer NOT NULL CHECK(frequency_seconds >= 60), enabled boolean NOT NULL DEFAULT true, next_run_at timestamptz NOT NULL, created_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), asset_id uuid REFERENCES assets(id), module_id text NOT NULL REFERENCES module_definitions(id), job_id uuid NOT NULL REFERENCES analysis_jobs(id), category text NOT NULL, status normalized_status NOT NULL, severity text NOT NULL, confidence confidence_level NOT NULL, title text NOT NULL, summary text NOT NULL, meaning text NOT NULL, impact text NOT NULL, suggested_action text NOT NULL, observed_at timestamptz NOT NULL, evidence_count integer NOT NULL DEFAULT 0, raw_reference text);
CREATE INDEX observations_asset_time_idx ON observations(organization_id,asset_id,observed_at DESC);
CREATE TABLE findings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), asset_id uuid REFERENCES assets(id), source_observation_id uuid REFERENCES observations(id), category text NOT NULL, severity text NOT NULL, priority text NOT NULL, confidence confidence_level NOT NULL, title text NOT NULL, description text NOT NULL, remediation text NOT NULL, status text NOT NULL CHECK(status IN ('OPEN','ACKNOWLEDGED','RESOLVED','ACCEPTED','FALSE_POSITIVE')), first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL, resolved_at timestamptz, resolved_by uuid REFERENCES users(id), risk_factors jsonb NOT NULL DEFAULT '{}');
CREATE INDEX findings_org_status_priority_idx ON findings(organization_id,status,priority,last_seen_at DESC);
CREATE TABLE evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), job_id uuid NOT NULL REFERENCES analysis_jobs(id), observation_id uuid REFERENCES observations(id), finding_id uuid REFERENCES findings(id), source text NOT NULL, content_type text NOT NULL, summary text NOT NULL, storage_key text, structured_data jsonb, checksum text, raw_access_required boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX evidence_finding_idx ON evidence(organization_id,finding_id,created_at);

CREATE TABLE vulnerabilities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), asset_id uuid NOT NULL REFERENCES assets(id), cve text, name text NOT NULL, description text NOT NULL, cvss_score numeric(3,1), cvss_version text, scanner_severity text NOT NULL, affected_service text, evidence_id uuid REFERENCES evidence(id), remediation text, first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL);
CREATE TABLE vulnerability_enrichments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vulnerability_id uuid NOT NULL REFERENCES vulnerabilities(id) ON DELETE CASCADE, provider text NOT NULL, cve text, description text, cvss jsonb, reference_urls jsonb NOT NULL DEFAULT '[]', known_exploited boolean, date_added date, required_action text, due_date date, fetched_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, UNIQUE(vulnerability_id,provider));
CREATE TABLE traffic_observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), asset_id uuid REFERENCES assets(id), job_id uuid NOT NULL REFERENCES analysis_jobs(id), source text NOT NULL, observation_type text NOT NULL, occurred_at timestamptz NOT NULL, summary jsonb NOT NULL, metadata_storage_key text);
CREATE INDEX traffic_org_time_idx ON traffic_observations(organization_id,occurred_at DESC);
CREATE TABLE pcap_artifacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), uploaded_by uuid NOT NULL REFERENCES users(id), storage_key text NOT NULL UNIQUE, original_filename text NOT NULL, content_length bigint NOT NULL CHECK(content_length >= 0), checksum text NOT NULL, captured_at timestamptz, uploaded_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, deleted_at timestamptz, classification text NOT NULL DEFAULT 'SENSITIVE');
CREATE TABLE reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), type text NOT NULL, title text NOT NULL, status text NOT NULL, parameters jsonb NOT NULL DEFAULT '{}', storage_key text, created_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE retention_policies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), category text NOT NULL CHECK(category IN ('PCAP','RAW_EVIDENCE','TRAFFIC_METADATA','JOB_OUTPUT','AUDIT','REPORTS')), retention_days integer CHECK(retention_days > 0), enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,category));
CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid REFERENCES users(id), type text NOT NULL, title text NOT NULL, body text NOT NULL, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), actor_user_id uuid REFERENCES users(id), actor_agent_id uuid REFERENCES agents(id), event_type text NOT NULL, resource_type text, resource_id text, request_id text, outcome text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', previous_hash text, event_hash text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_org_time_idx ON audit_events(organization_id,created_at DESC);

INSERT INTO permissions(name,description) VALUES
('assets.read','Read assets'),('assets.manage','Manage assets'),('scopes.read','Read authorized scopes'),('scopes.manage','Manage scopes'),('scopes.approve','Approve scopes'),('diagnostics.read','Read diagnostics'),('diagnostics.run','Run safe diagnostics'),('traffic.read','Read traffic analysis'),('pcap.upload','Upload PCAP'),('pcap.read','Read PCAP metadata'),('pcap.download','Download raw PCAP'),('pcap.delete','Delete PCAP'),('vulnerability.read','Read vulnerabilities'),('vulnerability.run','Run authorized vulnerability assessments'),('public_scan.run','Run modules against approved public scopes'),('findings.read','Read findings'),('findings.manage','Manage findings'),('evidence.raw.read','Read raw technical evidence'),('agents.read','Read agents'),('agents.manage','Manage agents'),('modules.read','Read modules'),('modules.manage','Manage modules'),('reports.read','Read reports'),('reports.create','Create reports'),('users.read','Read users'),('users.manage','Manage users'),('audit.read','Read audit events');

INSERT INTO roles(id,organization_id,name,system) VALUES
(gen_random_uuid(),NULL,'Owner',true),(gen_random_uuid(),NULL,'Administrator',true),(gen_random_uuid(),NULL,'Security Administrator',true),(gen_random_uuid(),NULL,'Security Analyst',true),(gen_random_uuid(),NULL,'Network Analyst',true),(gen_random_uuid(),NULL,'Operator',true),(gen_random_uuid(),NULL,'Viewer',true);

INSERT INTO role_permissions(role_id,permission_id)
SELECT r.id,p.id FROM roles r CROSS JOIN permissions p
WHERE r.system AND (
  (r.name='Owner' AND p.name<>'public_scan.run') OR
  (r.name='Administrator' AND p.name<>'public_scan.run') OR
  (r.name='Security Administrator' AND p.name IN ('assets.read','scopes.read','scopes.manage','scopes.approve','diagnostics.read','diagnostics.run','traffic.read','pcap.upload','pcap.read','pcap.download','pcap.delete','vulnerability.read','vulnerability.run','findings.read','findings.manage','evidence.raw.read','agents.read','agents.manage','modules.read','modules.manage','reports.read','reports.create','users.read','users.manage','audit.read')) OR
  (r.name='Security Analyst' AND p.name IN ('assets.read','scopes.read','diagnostics.read','diagnostics.run','traffic.read','pcap.upload','pcap.read','vulnerability.read','findings.read','findings.manage','reports.read','reports.create','agents.read','modules.read')) OR
  (r.name='Network Analyst' AND p.name IN ('assets.read','assets.manage','scopes.read','diagnostics.read','diagnostics.run','traffic.read','findings.read','reports.read','reports.create','agents.read','modules.read')) OR
  (r.name='Operator' AND p.name IN ('assets.read','scopes.read','diagnostics.read','diagnostics.run','findings.read','agents.read','modules.read','reports.read')) OR
  (r.name='Viewer' AND p.name IN ('assets.read','scopes.read','diagnostics.read','findings.read','agents.read','modules.read','reports.read'))
);
