DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE name IN ('services.read','services.manage','incidents.read','incidents.manage'));
DELETE FROM permissions WHERE name IN ('services.read','services.manage','incidents.read','incidents.manage');
DROP TABLE IF EXISTS change_observations;
DROP TABLE IF EXISTS operational_baselines;
DROP TABLE IF EXISTS monitor_samples;
DROP TABLE IF EXISTS route_comparisons;
DROP TABLE IF EXISTS route_hops;
DROP TABLE IF EXISTS route_snapshots;
DROP TABLE IF EXISTS incident_evidence_reports;
DROP TABLE IF EXISTS incident_evidence;
DROP TABLE IF EXISTS incident_links;
DROP TABLE IF EXISTS incident_events;
DROP TABLE IF EXISTS incidents;
DROP TABLE IF EXISTS evidence_artifacts;
DROP TABLE IF EXISTS evidence_references;
ALTER TABLE evidence DROP COLUMN IF EXISTS observed_at, DROP COLUMN IF EXISTS size_bytes, DROP COLUMN IF EXISTS artifact_kind, DROP COLUMN IF EXISTS vantage_point_id, DROP COLUMN IF EXISTS agent_id, DROP COLUMN IF EXISTS module_id;
DROP TABLE IF EXISTS job_cancellation_requests;
DROP TABLE IF EXISTS agent_result_receipts;
ALTER TABLE analysis_jobs DROP COLUMN IF EXISTS result_version, DROP COLUMN IF EXISTS result_identity, DROP COLUMN IF EXISTS authorization_reference, DROP COLUMN IF EXISTS protocol_version, DROP COLUMN IF EXISTS vantage_point_id, DROP COLUMN IF EXISTS diagnostic_run_id, DROP COLUMN IF EXISTS service_id;
ALTER TABLE schedules DROP COLUMN IF EXISTS parameters, DROP COLUMN IF EXISTS vantage_point_id, DROP COLUMN IF EXISTS service_id, DROP COLUMN IF EXISTS asset_id;
DROP TABLE IF EXISTS diagnostic_runs;
DROP TABLE IF EXISTS diagnostic_profiles;
DROP TABLE IF EXISTS network_services;
DROP TABLE IF EXISTS vantage_points;
ALTER TABLE agents DROP COLUMN IF EXISTS health_summary, DROP COLUMN IF EXISTS running_jobs, DROP COLUMN IF EXISTS available_slots, DROP COLUMN IF EXISTS heartbeat_interval_seconds, DROP COLUMN IF EXISTS capabilities_hash, DROP COLUMN IF EXISTS capabilities_manifest, DROP COLUMN IF EXISTS compatibility_status, DROP COLUMN IF EXISTS protocol_version;
ALTER TABLE module_definitions DROP COLUMN IF EXISTS result_schema_version, DROP COLUMN IF EXISTS parameter_schema_version, DROP COLUMN IF EXISTS supported_platforms, DROP COLUMN IF EXISTS protocol_version;
DROP TYPE IF EXISTS route_comparison_status;
DROP TYPE IF EXISTS incident_evidence_role;
DROP TYPE IF EXISTS root_cause_status;
DROP TYPE IF EXISTS incident_status;
DROP TYPE IF EXISTS agent_compatibility_status;
