import { useEffect,useState } from 'react'
import { Activity,Globe2,LockKeyhole,Network,Route,ShieldCheck } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { EmptyState } from '../components/EmptyState'
import { StatusBadge } from '../components/StatusBadge'
import { ApiError,apiGet } from '../services/api'
import type { NetworkService } from '../types'
interface ServiceResponse{data:NetworkService}
export function Service360Page(){const{id}=useParams();const[service,setService]=useState<NetworkService|null>(null);const[message,setMessage]=useState('Loading service context...');useEffect(()=>{if(!id)return;const controller=new AbortController();apiGet<ServiceResponse>(`/services/${id}`,controller.signal).then(result=>{setService(result.data);setMessage('')}).catch(error=>setMessage(error instanceof ApiError?`${error.message} (request ${error.requestId})`:'Service could not be loaded.'));return()=>controller.abort()},[id]);if(!service)return <EmptyState title={message} detail="Missing service evidence remains inconclusive."/>;const cards=[['Reachability','Awaiting vantage evidence',Activity],['DNS','No linked observation',Globe2],['TLS','No certificate conclusion',LockKeyhole],['HTTP','No transaction evidence',Network],['Route','No comparable snapshots',Route],['Security','No correlated finding',ShieldCheck]] as const;return <div className="space-y-6"><header className="card bg-gradient-to-r from-navy to-[#1e3d68] p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-blue-200">Service 360</p><div className="mt-2 flex flex-col justify-between gap-4 md:flex-row"><div><h1 className="text-3xl font-bold">{service.name} · {service.protocol.toUpperCase()} {service.port}</h1><p className="mt-2 text-sm text-slate-300">Asset {service.asset_id} · {service.product??'product not observed'} {service.version??''}</p></div><StatusBadge status={service.status} explanation="Service status reflects normalized observations, not a security guarantee."/></div></header><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,Icon])=><article className="card p-5" key={label}><Icon size={19} className="text-brand"/><p className="mt-4 text-xs font-bold uppercase text-slateblue">{label}</p><p className="mt-1 font-semibold">{value}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.3fr_1fr]"><div className="card p-5"><h2 className="font-bold">Vantage-point reachability</h2><div className="mt-4"><EmptyState title="No comparative evidence" detail="Run an authorized safe diagnostic from two or more vantage points to distinguish service-wide from location-specific behavior."/></div></div><aside className="card p-5"><h2 className="font-bold">Exposure and evidence</h2><p className="mt-3 text-sm leading-6 text-slateblue">Public exposure: <strong>{service.public_exposure?'Observed in an approved public scope':'Not currently recorded'}</strong>. This field alone does not imply vulnerability or compromise.</p></aside></section></div>}
